// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTZIcSrw3x2tZcJ86jL3CrGjp0BNLr3tI',
    appId: '1:483652263189:android:1b79219d77361541c85d1c',
    messagingSenderId: '483652263189',
    projectId: 'biteex-a3fa6',
    storageBucket: 'biteex-a3fa6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE-DdOGGqzH1QQF_gbbOnwMIgpLlVuw4A',
    appId: '1:483652263189:ios:3666f20add1af483c85d1c',
    messagingSenderId: '483652263189',
    projectId: 'biteex-a3fa6',
    storageBucket: 'biteex-a3fa6.firebasestorage.app',
    iosBundleId: 'com.biteExDelivery',
  );
}
